### ISSUE TITLE
Add "Use serviceworker" to Uppy Golden Retriever example

### ISSUE THREAD

**Issue by d12** [transloadit/uppy.io#129]
### Initial checklist

- [X] I understand this is a feature request and questions should be posted in the [Community Forum](https://community.transloadit.com/)
- [X] I searched [issues](https://github.com/transloadit/uppy/issues?q=is%3Aissue) and couldn’t find anything (or linked relevant results below)

### Problem

I was checking out https://uppy.io/examples/ and noticed that my files were never being properly resumed after a tab refresh, I always got the ghost. I was uploading 50-100mb video files. Based on the documentation I'd expect Golden Retriever to use the service worker to persist this file state between tab reloads. The example experience gave me the impression that Golden Retriever didn't really work well.

But then I checked the dev tools and noticed the examples page has no running service worker. So I assume Golden Retriever is just not caching the file because it's too large for IndexedDB.

### Solution

I'd have liked the examples page to either use service workers by default or include a checkbox for that. That way I can see if Golden Retriever works as expected for my file size before moving forward with integration.

### Alternatives

More documentation on the size limitations would also be handy. How large of a file can be resumed? What is the exact cutoff for caching a file between page loads using the service worker?

**Comment by Murderlon** [comment]
> More documentation on the size limitations would also be handy. How large of a file can be resumed? What is the exact cutoff for caching a file between page loads using the service worker?

There is an issue for this already: https://github.com/transloadit/uppy.io/issues/123
