### ISSUE TITLE
Add back Uppy Contributing page

### ISSUE THREAD

**Issue by mifi** [transloadit/uppy.io#134]
I think this page got lost during transition from old docs to uppy.io:

https://github.com/transloadit/uppy/blob/main/.github/CONTRIBUTING.md

It contains a lot of useful information when developing Uppy/Companion. In particular how to setup Remote Providers apps, keys, scopes etc. For example I struggled finding how to test Zoom, until I stumbled upon that file while googling for a solution.

Maybe we can move the provider-specific info from the contributing page into each provider's page in the new docs.

- [ ] we should probably also delete that file, or have it redirect to uppy.io

**Comment by Murderlon** [comment]
I did it on purpose, if people want to contribute, they need to be in the repo anyway so I didn't see the need to also put it on the website

**Comment by mifi** [comment]
gotha!

could we maybe link from uppy.io somewhere to https://github.com/transloadit/uppy/blob/main/.github/CONTRIBUTING.md ? I couldn't find the file anywhere

should we move the [i18n contribution guide](https://uppy.io/docs/locales/#contributing-a-new-language) also into https://github.com/transloadit/uppy/blob/main/.github/CONTRIBUTING.md ?

**Comment by Murderlon** [comment]
> could we maybe link from uppy.io somewhere to https://github.com/transloadit/uppy/blob/main/.github/CONTRIBUTING.md ? I couldn't find the file anywhere

How about the footer?

> should we move the [i18n contribution guide](https://uppy.io/docs/locales/#contributing-a-new-language) also into https://github.com/transloadit/uppy/blob/main/.github/CONTRIBUTING.md ?

Not sure, the guide is for using locales, not contributing to them. But we can add something to the contributing file about where to find the locale files and how they work, that would be nice!

**Comment by mifi** [comment]
> How about the footer?
> 
added it to the footer and also added footer to all pages (it was only shown on the front page)

> Not sure, the guide is for using locales, not contributing to them. But we can add something to the contributing file about where to find the locale files and how they work, that would be nice!

https://github.com/transloadit/uppy/pull/4591
