### ISSUE TITLE
Add docs versioning & automate Uppy version references

### ISSUE THREAD

**Issue by Murderlon** [transloadit/uppy.io#15]
Important read: https://docusaurus.io/docs/versioning
Note that the first version of this website when it's done would be the only historic version. We can't recreate from another structure, but that's fine, as of then we will have versioned docs.

Hooks like this could be used for references to versions in docs:

https://github.com/facebook/docusaurus/blob/13e7de853e0f0968916b60bae769bd49d224a19d/packages/docusaurus-plugin-content-docs/src/client/index.ts#L72

We need a smart way to have a single source of truth for things like this:

https://github.com/transloadit/uppy.io/blob/58eb8828bcb9d602374e9d166d707fff1cbdc8d7/docs/user-interfaces/dashboard.mdx?plain=1#L58

Inspiration how it's used:
https://github.com/facebook/docusaurus/blob/main/website/src/components/UpgradeGuide/index.tsx#L40=

**Comment by Murderlon** [comment]
This may or may not depend on #14

**Comment by mifi** [comment]
Not sure if we **really** want versioning. From their docs:

> :warning: Think about it before starting to version your documentation - it can become difficult for contributors to help improve it!

> Most of the time, you don't need versioning as it will just increase your build time, and introduce complexity to your codebase. Versioning is best suited for websites with high-traffic and rapid changes to documentation between versions. If your documentation rarely changes, don't add versioning to your documentation.

Do we really have rapid changes to docs between versions, that render docs incompatible? (other than majors)

**Comment by Murderlon** [comment]
Fair point. I just thought it was nice majors but now that I think about it, it's much easier to use a migration guide and compare versions of docs. So we can skip this indeed

**Comment by Murderlon** [comment]
Closed in #28
