### ISSUE TITLE
Docs don't include reference to Vue.js Dashboard modal

### ISSUE THREAD

**Issue by prattcmp** [transloadit/uppy.io#160]
I spent a ton of time trying to figure out how to get the Vue.js plugin to function as a modal only to find there was a hidden dashboard-modal Vue.js component not listed in the documentation. Then, I stumbled upon this blog: https://uppy.io/blog/2020/11/1.23/

Please add the following to the docs:
```
<dashboard /> - renders an inline @uppy/dashboard
<dashboard-modal /> - renders a @uppy/dashboard modal
```

Docs: https://github.com/transloadit/uppy.io/blob/main/docs/framework-integrations/vue.mdx

**Comment by Murderlon** [comment]
Good catch! Want to contribute a PR?
