### ISSUE TITLE
Use with your own server section of AWS S3 contains misleading routes

### ISSUE THREAD

**Issue by nerg4l** [transloadit/uppy.io#213]
The routes provided in the "[Use with your own server](https://uppy.io/docs/aws-s3-multipart/#use-with-your-own-server)" of AWS S3 uploader shows different endpoints than the endpoints used in the linked "[Setup Uppy](https://github.com/transloadit/uppy/blob/main/examples/aws-nodejs/public/index.html)" example.

https://github.com/transloadit/uppy.io/blob/6a5a3bc89cabd80e01b289e136783002ea9b38ab/docs/uploader/aws-s3-multipart.mdx?plain=1#L143-L151

From the [Setup Uppy example](https://github.com/transloadit/uppy/blob/6673b7787771194c52f0cb451bb1f3f69f8af71d/examples/aws-nodejs/public/index.html):

- `/sts`
- `/sign-s3`
- `/s3/multipart`
- `/s3/multipart/${uploadId}`
- `/s3/multipart/${uploadId}/${partNumber}`
- `/s3/multipart/${uploadId}/complete`

**Comment by Murderlon** [comment]
They are the same, it just shows that if you have an existing backend, perhaps even with existing s3 endpoints , you can just group them under `/uppy` route of whatever you'd like to do.

**Comment by nerg4l** [comment]
Are you sure that only the price is different?

- `/uppy/sts`
- `/uppy/s3`
- `/uppy/s3-multipart`
- `/uppy/s3-multipart/:id`
- `/uppy/s3-multipart/:id/:partNumber`
- `/uppy/s3-multipart/:id/complete`

The documentation uses `s3-multipart` but the linked code example uses `s3/multipart`. Also the sign route is completely different.

**Comment by Murderlon** [comment]
Maybe the docs are misleading, but it just needs to match. You can do this if you want:

On the server:
```js
app.post('/my/supercool/endpoint', (req, res, next) => {}
```

And then on the client:

```js
const response = await fetch('/my/supercool/endpoint', {
  method: 'POST',
  // Send and receive JSON.
  headers: {
    accept: 'application/json',
  },
  body: serialize({
    filename: file.name,
    type: file.type,
    metadata,
  }),
  signal,
})
```

It's a lot of manual work. Ideally, we'd have `@uppy/server-functions` which you can use on the server, and force people to have the same endpoints as companion. Then I think you wouldn't need to manually write this.

**Comment by nerg4l** [comment]
Agreed, a companion compatible uploader config would be even better.

I was considering this option but could not find any documentation of the current endpoints used by Companion. I can dig through the code of course but I would prefer to have it in a more readable way.

**Comment by Murderlon** [comment]
I created two issues for it:
- https://github.com/transloadit/uppy/issues/5033
- https://github.com/transloadit/uppy/issues/5030

In the meantime if you're willing to contribute a PR to make the writing more clear in the current docs that would be great :)
