### ISSUE TITLE
AWS S3 references @uppy/aws-s3

### ISSUE THREAD

**Issue by nerg4l** [transloadit/uppy.io#216]
The documentation of AWS S3 Uploader with `aws-s3-multipart` slug references `@uppy/aws-s3` but not `@uppy/aws-s3-multipart`. Is this intentional? I'm quite sure it should reference `@uppy/aws-s3-multipart`.

https://github.com/transloadit/uppy.io/blob/6a5a3bc89cabd80e01b289e136783002ea9b38ab/docs/uploader/aws-s3-multipart.mdx

Even the documentation says `@uppy/aws-s3-multipart` is going to be the only implementation in the next semver.

> Opt-in to using the multipart plugin, which is going to be the only S3 plugin as of the next semver.

https://github.com/transloadit/uppy/blob/37d0a03390b4e704949dbe5f2bfc9e116e3cba1c/packages/%40uppy/aws-s3/src/index.js#L116

**Comment by Murderlon** [comment]
In the next major, all `aws-s3-multipart` code will move into `aws-s3` and `aws-s3-multipart` will be deprecated. So `aws-s3` is the plugin you want to be on.

**Comment by nerg4l** [comment]
Thanks
