### ISSUE TITLE
Add note about not wrapping in `form`

### ISSUE THREAD

**Issue by mifi** [transloadit/uppy.io#51]
Something like:
> Warning: Be careful not to wrap your Uppy root HTML element in a `<form>`, and make sure there is no form lower in the HTML tree. If there is a `<form>` element anywhere below Uppy's root element, it will capture submit events from plugins like Unsplash and URL (and possibly others).

Not sure where to write this though, any thoughts?

(This mistake broke for submit on all demos on transloadit.com)

**Comment by Murderlon** [comment]
Good one. I think it should be in all UI plugin's under the `target` option and in the "Creating your own UI" guide.

**Comment by mifi** [comment]
Alternatively we could explore the possibility of having a <form> internally inside the Uppy plugins, what do you think?

**Comment by Murderlon** [comment]
I think part of you comment is missing 😅 (`having a ....`).

**Comment by mifi** [comment]
Oops! Markdown took my `<form>` a bit too literaly 😄

**Comment by Murderlon** [comment]
So you mean a form inside Uppy? Could be worth exploring yeah

**Comment by mifi** [comment]
yes, we had a thread about it on slack. @arturi is exploring whether we can handle form submits from inside upp without having a form at all.

**Comment by aduh95** [comment]
I think we can close this in favor of not putting any `<form>` element in the Uppy DOM tree, as discussed in the Uppy call :)
