### ISSUE TITLE
many users confused by the fact that you need to define plugins twice

### ISSUE THREAD

**Issue by mifi** [transloadit/uppy.io#66]
see https://community.transloadit.com/t/uppy-uploads-the-original-image-instead-of-the-edited-version/16440/2

was previously discussed here https://github.com/transloadit/uppy/pull/4223

we should either remove the need to specify plugins twice, or document it so it's clear (in the react docs)

**Comment by kvz** [comment]
There is a PR open to address this: https://github.com/transloadit/uppy/pull/4343
